name: Build container image and publish it on ghcr.io
on:
  [workflow_dispatch]

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker buildx build . --platform linux/amd64 --tag raffomartini/cgt-calc:latest
      - name: publish
        run: |
          docker push raffomartini/cgt-calc:latest