name: Publish cgt-calc container
on:
  [workflow_dispatch]

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker buildx build . --platform linux/amd64 --tag ghcr.io/raffomartini/cgt-calc:latest
      - name: publish
        run: |
          docker login -u raffomartini -p ${{ secrets.GHCR_TOKEN }} ghcr.io
          docker push ghcr.io/raffomartini/cgt-calc:latest