name: Publish cgt-calc.

on:
  [workflow_dispatch]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: gcr-calc

jobs:
  build-and-push-container-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v4
      
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

    #   - 
    #     name: build
    #     run: |
    #         docker buildx build . --platform linux/amd64 --tag ghcr.io/raffomartini/cgt-calc:latest

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - 
        name: Build and push
        uses: docker/build-push-action@v5
        with:
            context: .
            platforms: linux/amd64
            push: true
            tags: |
              ghcr.io/raffomartini/cgt-calc

    #   - 
    #     name: publish
    #     run: |    
    #       docker push ghcr.io/raffomartini/cgt-calc:latest
